name: Archibus-Automated-Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "45 15 * * 2"  # 11:45 AM Eastern (EDT)



jobs:
  archibus-automated-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Composite Action
        uses: ./ # use ./ for local dev.
        with:
          scheduling_args: ${{ secrets.ARCHIBUS_SECRET }} 
